   ## CREATE AWS INFRASTRACTURE AND CONFIGURE SSH ACCESS
   - name: terrafrom AWS creation
     delegate_to: localhost
     block:

     # terraform
     - name: Create AWS infraestructure
       terraform:
        project_path: ./terraform 
        force_init: true
        state: present 
        variables:
           instance_name: "{{ instance_name }}" 
           server_ip: "{{ server_ip | default() }}"
           instance_type: "{{ instance_type }}"
           key_name: "{{ key_name }}"
           schedule_tag: "{{ schedule_tag }}"
           data_volume_size: "{{ data_volume_size }}"
           wal_volume_size: "{{ wal_volume_size }}"
           temp_volume_size: "{{ temp_volume_size }}"
           #report_volume_size: "{{ report_volume_size }}"
           #file_server_id: "{{ file_server_id }}"
           #file_server_az: "{{ file_server_az }}"
       register: terraform
       tags: [ create_only ]
     
     # wait for server creation
     - name: wait for created host
       wait_for: 
        port: 22
        host: '{{ terraform.outputs.instance_ip_addr.value }}'
        search_regex: OpenSSH
        delay: 1
     
     # enable ssh access for ansible scripts
     - name: post-create script
       shell: scripts/enable_ansible.sh {{ vault_key_prefix }}-{{ key_name }}.pem {{ vault_root_password }}
       tags: [ enable_ansible ]

     tags: [ create ]

