---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: postgresql96
    image: ubuntu:18.04
  - name: postgresql10
    image: ubuntu:18.04
  - name: postgresql11
    image: ubuntu:18.04
  - name: postgresql12
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      postgresql96:
        postgresql_version: "9.6"
      postgresql10:
        postgresql_version: "10"
      postgresql11:
        postgresql_version: "11"
      postgresql12:
        postgresql_version: "12"
  playbooks:
    converge: ../resources/playbook.yml
scenario:
  name: ubuntu1804
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
